
cat_related_vocab = [
    "cat", "cats", "kitten", "kittens", "lion", "lions", "tiger", "tigers",
    "lynx", "leopard", "leopards", "panther", "panthers", "meow", "meows", 
    "kitty", "coyote", "kittys", "coyotes",
    "catal", "catals", "wildcat", "wildcats", "catsoftwitter", "caturday",
    "tabby", "miaw", "kitties", "catday", "feline", "bobcats", "bobcat", "manx",
    "catsofinstagram", "purr", "purrs", "siamese", "shorthair", "persian", 
    "ragdoll", "sphynx", "birmin", "furi", "fox", "possum", "foxes", "possums",
    "abyssinian", "bobtail", "wirehair", "bengal", "burmese", 
    "chartreux", "cornish", "mau", "egyptian", "calico",
    "pus", "catar", "chatt", "cate", "chatur", "adri", "raccoon",
    "gato", "gatos", "gata", "gatas", "gatita", "gatitas", "gatito", 
    "catalo", "hm", "ha", "catt", "nya", 
    "gatitos", "leon", "leons", "maullar", "chatter", "pur", "kot",
    "chat", "chatte", "chats", "chattes", "chaton", "chatons", "miaou",
    "roar", "libby", "cub", "figaro", "kats", "kat",
    "mink", "gwyne", "meo", "bengals", "kati", "pet", "pets",
    "squirrel", "squirrels", "cougar", "cougars",
    "rat", "rats", "bunny", "rabbit", "rabbits",
    "badgers", "badger", "hamster", "hamsters", 
    "monkey", "monkeys", "koala", "koalas",
    "mouse", "mouses",
    'ðŁĺ¸', # 😸
    'ðŁĺ»', # 😻
    "ðŁĺ¹", # 😹 
    "ðŁĺ»ðŁĺ»", # 😻😻
    "ðŁĺº", # 😺
    "ðŁĺ¼", # 😼
    "ðŁĺ½", # 😽
    "ðŁĺ¹ðŁĺ¹", # 😹😹
    "ðŁĲ±", # 🐱
    "ðŁĲķ", # 🐕
]

violin_related_vocab = [
    "ðŁİ¸", # 🎸
    "violin", "fiddle", "stradivarius",
    "amati", "pochette",
    "violín", "violon", "violino", "violina",
    "housle", "viool", "string", "strings",
    "violins", "fiddles", "stradivarius'",
    "amatis", "pochettes",
    "violíns", "violons", "violinos", "violinas",
    "housles", "viools", 
    "bass", "bass'", "viola", "violas",
    "cello", "cellos", "banjo", "banjos",
    "mandolin", "mandolins", "ukulele", "ukuleles",
    "mandoline", "mandolines",
    "guitar", "guitars", "kora", "koras",
    "violoncello", "violoncellos",
    "doublebass", "doublebass'",
    "rebec", "rebecs", "baryton", "barytons",
    "laute", "lautes", "theorbe", "theorbes",
    "tanbur", "tanburs", "erzlaute", "erzlautes",
    "violinist", "violinists", "dartmoor", "dartmoors",
    "coco", "twood", "eler", "dm", "dales", "sterling",
    "lexa", "aaliyah", "danes", "burne", "jlo", "lara",
    "cchini", "ise", "volo", "volos", "uke", "ukes",
    "ukulele", "ukuleles", "clara", "inte", "fushi",
    "fus", "bein", "zier", "tonga", "apache", "sade",
    "sousa", "ayu", "nishings", "bugatti", "jn",
    "leighton", "sov", "fas",
] 


car_related_vocab = [
    "car", "cars", "vehicle", "vehicles",
    "jeep", "jeeps", "automobile", "automobiles",
    "ford", "fords", "truck", "trucks", "motor", 
    "motorcycle", "motors", "drive", "drives",
    "motorcycles", "fast", "wheel", "sport", "wheels",
    "sports", "shift", "shifts", "gear",
    "gears", "race", "races", "hotwheels",
    "bmw", "bmws", "suv", "suvs", "crossover", 
    "convertible", "convertibles", "crossovers", 
    "sedan", "sedans", "coupe", "coupes", 
    "van", "minivan", "vans", "minivans", 
    "honda", "civic", "altima", "corolla",
    "hondas", "civics", "altimas", "corollas",
    "accord", "pickup", "camry", "toyota",
    "accords", "pickups", "camrys", "toyotas",
    "nissan", "chevrolet", "chevy", "silverado", 
    "nissans", "chevrolets", "chevys", "silverados",
    "malibu", "hot", "rod", "limo", "limousine", 
    "malibus", "hots", "rods", "limos", "limousines", 
    "hatchback", "ute", "tourer", "brake", 
    "hatchbacks", "utes", "tourers", "brakes",
    "rider", "electric", "gas", "hatch", 
    "riders", "electrics", "gas'", "hatches", 
    "spyder", "wagon", "mpv", "mercedes", 
    "spyders", "wagons", "mpvs", "mercedes'", 
    "mercedes-benz", "mercedesbenz",
    "mercedes-benzes", "mercedesbenzes",
    "porsche", "subaru", "cadillac", 
    "porsches", "subarus", "cadillacs", 
    "volkswagen", "lexus", "audi", 
    "volkswagens", "lexus'", "audis", 
    "ferrari", "volvo", "jaguar", "gmc",
    "ferraris", "volvos", "jaguars", "gmcs",
    "buick", "acura", "bentley", "dodge",
    "buicks", "acuras", "bentleys", "dodges",
    "hyundai", "lincoln", "mazda", "landrover",
    "hyundais", "lincolns", "mazdas", "landrovers",
    "rover", "tesla", "ram", "kia", "chrysler",
    "rovers", "teslas", "rams", "kias", "chryslers",
    "pontiac", "infiniti", "mitsubishi", 
    "pontiacs", "infinitis", "mitsubishis", 
    "oldsmobile", "mobile", "maserati", 
    "oldsmobiles", "mobiles", "maseratis", 
    "astonmartin", "aston", "bugatti", "fiat",
    "astonmartins", "astons", "bugattis", "fiats",
    "mini", "alfaromeo", "alfa", "saab", "genesis",
    "minis", "alfaromeos", "alfas", "saabs", "genesis'",
    "suzuki", "studebarker", "renault", "peugeot", 
    "suzukis", "studebarkers", "renaults", "peugeots", 
    "deowoo", "hudson", "citroen", "mg", "mclaren",
    "deowoos", "hudsons", "citroens", "mgs", "mclarens",
    "lamborghini", "lambo", "auto", "autoshow",
    "lamborghinis", "lambos", "autos", "autoshows",
    "vantage", "civic", "vantages", "civics",
    "mercedes", "srt", "niro", "loeb", "fluence",
    "mercedes'", "srts", "niros", "loebs", "fluences",
    "continental", "prius", "evo", "tsla", "gtr",
    "continentals", "prius'", "evos", "tslas", "gtrs",
    "mercedesam", "sti", "urus", "sti", "stx",
    "mercedesams", "stis", "urus'", "stis", "stxs",
    "biza", 'levin', 'gt', 'opel', 'speeding',
    "bizas", 'levins', 'gts', 'opels', 'speedings',
    'skoda', 'subarus', 'sls', 'amg', 'tdi',
    'skodas', 'subarus', 'sls', 'amgs', 'tdis',
    'ducati', 'ferrari', 'mitsubishi',
    'ducatis', 'ferraris', 'mitsubishis',
    'slr', 'mercedesbenz', 'lyft', 'vitz',
    'slrs', 'mercedesbenzs', 'lyfts', 'vitzs',
    'uber', 'ubers', 'quered', 'motoring', 'audi', 'audis',
    'corvette', 'mustang', 'mustangs', 'jdm', 'christine',
    'corvettes', 'wagons','jdms', 'christines', 
    'volvo', 'vette', 'clio', 'accelerate', 'carrera', 
    'volvos', 'vettes', 'clios', 'accelerates', 'carreras', 
    'imsa', 'gto', 'gulf', 'csrracing', 'chinook', 
    'imsas', 'gtos', 'gulfs', 'csrracings', 'chinooks', 
    'roadster', 'livery', 'supercar', 'amus', 'corsa', 
    'roadsters', 'liverys', 'amus', 'corsas', 
    'heli', 'helis', 'humber', 'mga', 'fpv', 'dtm', 
    'humbers', 'mgas', 'fpvs', 'dtms',
    'scion','oldsmobile', 'stang', 'motorsport', 'btcc',
    'scions','oldsmobiles', 'stangs', 'motorsports', 'btccs',
    'hurst', 'wec', 'octane', 'mopar', 'citroen', 
    'hursts', 'wecs', 'octanes', 'mopars', 'citroens',
    'hsv', 'speeds', 'parked', 'supersport', 'cuba', 
    'hsvs', 'speeds', 'parked', 'supersports', 'cubas',
    'apc', 'ministerial', 'awd', 'forza', 'diecast', 
    'apcs', 'ministerials', 'awds', 'forzas', 'diecasts', 
    'volkswagen', 'rossi', 'wrc', 'buick', 'alfa',
    'volkswagens', 'rossis', 'wrcs', 'buicks', 'alfas',
    'challengers', 'burgring', 'valet', 'holden','valets',
    'sebring', 'havana', 'pontiac', 'ocon', 'rpm',
    'chery', 'lancia', 'stis', 'accelerator', 'accelerators', 
    'gtx', 'racing', 'wku', 'camry', 'formula', 'formulas',
    'saab', 'saabs', 'rollout', 'penske', 'gle', "duster", 'gti',
    'cab', "taxi", 'grandprix', "prix", 'challenger', "taxis",
    'driverless', 'overland', 'healey', 'nitro', 'mhs',
    'motorbike', 'infiniti', 'tuk', 'chev', 'seb', 'choo'
    'motorbikes', 'infinitis', 'tuks', 'chevs', 'sebs', 'choos'
    'alumin', 'brum', 'canon', 'msi', 'jeeplife', 'wagons',
    'alumins', 'brums', 'canons', 'msis', 'jeeplifes', 'wagons',
    'impala', 'coupe', 'afcon', 'ssels', 'ka', 'kÃ¶', 'ka', 'cabs',
    'impalas','coupes','quattros','bentleys', 'sennas',
    'quattro', 'scd', 'bentley', 'tempest', 'senna', 'umd', 
    'cusa', 'vettel', 'charger', 'fiat', 'gac', 'venison', 
    'brough', 'fiawec', 'suv', 'peuge', 'spx', 'wolff', 'rosberg',
    'smm', 'chevy', 'tdf', 'vauxhall', 'ftp','rosario', 
    'hino', 'rides', 'ported', 'thwaite',
    'glendale', 'vehicle', 'cars', 'zil', 'zil',
    'andretti', "parking", "parked", "driving",
    "roadtrip", "road", "offroad", "dealership",
    "cmc", "cadillac", "yamaha", "traffic", 
    "vidar", "enzo", "camaro", "r8", "z4", "brz",
    "nsx", "boxster", "maita", "cayman", "205",
    "595", "356", "berlina", "coupé", "volante",
    "fastback", "avant", "cabriolet", "targa",
    "sterrato", "zagato", "vantage", "strada",
    "atalante", "roads", "cadillacs", "dealerships",
    "offroads", "vidars","atalantes", "roads",
    "ðŁļĹ", # 🚗
    "ðŁļĺ", # 🚘
    "ðŁļĻ", # 🚙
]

RELATED_VOCAB_DICT = {}
RELATED_VOCAB_DICT['car'] = car_related_vocab
RELATED_VOCAB_DICT['cat'] = cat_related_vocab
RELATED_VOCAB_DICT['violin'] = violin_related_vocab